### ISSUE TITLE
Help with setting up pushnotify in Ubuntu

### ISSUE THREAD

**Issue by hackboxlive** [clearnote01/pushnotify#1]
Forgive me for my inexperience, but after getting the access token from the pushbullet, I ran `main.py` and nothing happened. I tried running the battery command, nothing prints.

**Comment by clearnote01** [comment]
1. Do you have "acpi" installed? That is a dependency for battery and thermal plugins.

2. If answer of above is yes then does uptime and monitor plugin work for you?

**Comment by hackboxlive** [comment]
No worries. I somehow managed to resolve some dependencies. That's it!
